/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Fide_Cars;

import java.awt.BorderLayout;
import javax.swing.JTabbedPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author maria
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        JTabbedPane tabbedPane = new JTabbedPane();
        
        PanelInventario panelInventario = new PanelInventario();
        PanelFacturacion panelFacturacion = new PanelFacturacion();
        PanelClientes panelClientes = new PanelClientes();

        
        tabbedPane.addTab("Inventario", panelInventario);
        tabbedPane.addTab("Facturación", panelFacturacion);
        tabbedPane.addTab("Clientes", panelClientes);

        
        add(tabbedPane, BorderLayout.CENTER);

       
        setSize(800, 600);
        setLocationRelativeTo(null);  

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  public static void main(String[] args) {
        /* Crear y mostrar la ventana principal */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }
}
        /* Create and display the form */
    
            
     
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

